version: "4.12"

services:
  pgdb:
    container_name: pgdb_lojavirtual
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  esearch:
    container_name: search
    image: elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
